const TRANSLATIONS = {
  en: {
    home: 'Home',
    my_quizzes: 'My quizzes',
    discover: 'Discover',
    search_placeholder: 'Search',
    new_quiz: 'New quiz',
    my_collections: 'My collections',
    all_quizzes: 'All quizzes',
    new_folder: 'New folder',
    saved: 'Saved',
    favorites: 'Favorites',
    history: 'History',
    settings: 'Settings',
    profile: 'Profile',
    theme: 'Theme',
    language: 'Language',
    help: 'Help',
    log_out: 'Log out',
    delete: 'Delete',
    folder_name_placeholder: 'Folder name',
    general_info: 'General information',
    quiz_structure: 'Quiz structure',
    settings_confirmation: 'Settings & confirmation',
    step_of: 'Step',
    of: 'of',
    quiz_name: 'Quiz name',
    quiz_name_placeholder: 'Biology - Animal Cell',
    description: 'Description',
    description_optional: 'optional',
    description_placeholder: 'A short description for participants...',
    subject_category: 'Subject / Category',
    choose_subject: 'Choose subject...',
    language_label: 'Language',
    visibility: 'Visibility',
    public: 'Public',
    public_desc: 'Everyone can access',
    private: 'Private',
    private_desc: 'Link only',
    draft: 'Draft',
    draft_desc: 'Not publicly visible',
    num_questions: 'Number of questions',
    between_1_100: 'Between 1 and 100',
    time_per_question: 'Time per question',
    time_hint: '5 – 300 seconds',
    answer_choices: 'Answer choices',
    choices_per_q: 'Choices per question:',
    question_type: 'Question type',
    type_hint: 'can be changed per question in the editor',
    single_answer: 'Single answer',
    single_desc: 'one correct option',
    multiple_answers: 'Multiple answers',
    multiple_desc: 'several correct options',
    true_false: 'True / False',
    true_false_desc: 'forces 2 choices',
    behaviour: 'Behaviour',
    question_order: 'Question order',
    answer_order: 'Answer order',
    fixed: 'Fixed',
    random: 'Random',
    allowed_attempts: 'Allowed attempts',
    min_pass_score: 'Minimum pass score (%)',
    points_correct: 'Points per correct answer',
    display_options: 'Display options',
    show_final_score: 'Show final score',
    correct_answers: 'Correct answers',
    visible_timer: 'Visible timer',
    question_progress: 'Question progress',
    allow_skip: 'Allow skip',
    summary: 'Summary',
    back: 'Back',
    cancel: 'Cancel',
    continue: 'Continue',
    create_quiz: 'Create quiz',
    creating: 'Creating...',
    no_quizzes_title: 'No quizzes yet',
    no_quizzes_sub: 'Click New quiz to create your first one.',
    my_quizzes_title: 'My quizzes',
    quiz_word: 'quiz',
    quizzes_word: 'quizzes',
    draft_label: 'Draft',
    published_label: 'Published',
    filled: 'filled',
    edit: 'Edit',
    daily_quiz: 'Daily quiz',
    trending: 'Trending this week',
    recommended: 'Recommended for you',
    see_all: 'See all',
    show_less: 'Show less',
    all: 'All',
    results_for: 'Results for',
    found: 'found',
    no_quizzes_found: 'No quizzes found',
    no_quizzes_found_sub: 'Try a different keyword or browse by category.',
    history_title: 'History',
    no_history_title: 'No history yet',
    no_history_sub: 'Quizzes you play will appear here',
    correct: 'correct',
    notifications: 'Notifications',
    no_notifs_title: 'No notifications yet',
    no_notifs_sub: "You're all caught up!",
    notif_count: 'notification',
    notifs_count: 'notifications',
    clear_all: 'Clear all',
    just_now: 'Just now',
    ago: 'ago',
    mode: 'Mode',
    single_player: 'Single player',
    single_player_desc: 'Practice on your own',
    multiplayer: 'Multiplayer',
    multiplayer_desc: 'Play with others',
    save: 'Save',
    saved_label: 'Saved',
    start_quiz: 'Start quiz',
    questions: 'Questions',
    time_per_q: 'Time / question',
    points_per_correct: 'Points / correct',
    pass_score: 'Pass score',
    add_question: 'Add question',
    question_text_placeholder: 'Type your question here...',
    time_sec: 'Time (sec)',
    points: 'Points',
    type: 'Type',
    single_type: 'Single',
    multiple_type: 'Multiple',
    true_false_type: 'True / False',
    answers_label: 'Answers',
    answers_hint: '(click the icon to mark correct)',
    previous: 'Previous',
    next: 'Next',
    save_btn: 'Save',
    publish_quiz: 'Publish quiz',
    no_folders: 'No folders yet',
    get_ready: 'Get ready!',
    almost: 'Almost...',
    go: 'Go!',
    skip: 'Skip',
    times_up: "Time's up!",
    incorrect: 'Incorrect - correct answer:',
    see_results: 'See results',
    perfect_score: 'Perfect score!',
    quiz_passed: 'Quiz passed!',
    keep_practicing: 'Keep practicing!',
    scored_above: 'You scored',
    above_pass: 'above the',
    pass_mark: 'pass mark.',
    scored_below: "You scored",
    below_pass: "the pass mark is",
    youve_got_this: "You've got this!",
    score: 'Score',
    accuracy: 'Accuracy',
    time: 'Time',
    try_again: 'Try again',
    back_to_quizzes: 'Back to quizzes',
    profile_title: 'Profile',
    no_email: 'No email',
    help_title: 'Help',
    help_1_title: 'Getting started',
    help_1_desc: 'Click New quiz to create your first quiz. Add questions, set a timer and publish.',
    help_2_title: 'Playing a quiz',
    help_2_desc: 'Browse quizzes in Discover, click one and press Start quiz. Answer before the timer runs out.',
    help_3_title: 'Saving quizzes',
    help_3_desc: 'Click the bookmark icon on any quiz to save it to your Favorites in the sidebar.',
    help_4_title: 'Contact',
    help_4_desc: 'Reach out via Telegram or Instagram — links in the footer of the main page.',
    toast_not_logged: 'You are not logged in',
    toast_saved: 'Quiz saved successfully!',
    toast_published: 'has been published successfully.',
    toast_already_logged: 'You are already logged in.',
    toast_daily_unavailable: 'Daily quiz not available',
    toast_login_to_create: 'Please log in to create a quiz',
    delete_confirm: 'Delete?',
    yes: 'Yes',
    no: 'No',
    start_now: 'Start now',
    max_questions_reached: 'Maximum 100 questions reached',
    max_answers: 'Maximum 6 answers',
    add_answer: 'Add answer',
    cat_mathematics: 'Mathematics',
    cat_sciences: 'Sciences',
    cat_history: 'History',
    cat_geography: 'Geography',
    cat_literature: 'Literature',
    cat_technology: 'Technology',
    cat_arts: 'Psychology',
    cat_sports: 'Sports',
    cat_languages: 'Languages',
    cat_general: 'Other',
    trending_label: 'Trending',
    recommended_label: 'Recommended for you',
    summary_name: 'Name',
    summary_subject: 'Subject',
    summary_questions: 'Questions',
    summary_time_q: 'Time / question',
    summary_answer_choices: 'Answer choices',
    summary_visibility: 'Visibility',
    summary_attempts: 'Attempts',
    summary_pass_score: 'Pass score',
    summary_points: 'Points / correct',
    summary_sec: 'sec.',
    editor_back: 'Back',
    editor_add_question: 'Add question',
    editor_question_label: 'Question text',
    editor_answers_label: 'Answers',
    editor_answers_hint: '(click the icon to mark correct)',
    editor_save: 'Save',
    editor_publish: 'Publish quiz',
    editor_prev: 'Previous',
    editor_next_q: 'Next',
    editor_q_of: 'Question',
    editor_of: 'of',
    editor_option_single: 'Single',
    editor_option_multiple: 'Multiple',
    editor_option_truefalse: 'True / False',
    editor_add_answer: 'Add answer',
    editor_max_answers: 'max',
    editor_no_folders: 'No folders yet',
    editor_answer_placeholder: 'Answer',
    runner_next: 'Next',
    runner_see_results: 'See results',
    runner_correct_prefix: 'Correct! +',
    runner_correct_suffix: ' points',
    runner_q_of: 'Question',
    runner_of: 'of',
    info_questions: 'Questions',
    info_time_q: 'Time / question',
    info_points: 'Points / correct',
    info_pass: 'Pass score',
    contact: 'Contact',
    logout: 'Log out',
    contact_title:      'Get in touch',
    contact_sub:        "We'll get back to you as soon as possible",
    contact_to_label:   'To',
    contact_subj_label: 'Subject',
    contact_subj_ph:    "What's this about?",
    contact_msg_label:  'Message',
    contact_msg_ph:     'Your message...',
    contact_send:       'Send message',
    contact_sent:       'Message sent!',
    contact_socials:    'Or reach out on socials',
  },
  ro: {
    home: 'Acasă',
    my_quizzes: 'Quiz-urile mele',
    discover: 'Descoperă',
    search_placeholder: 'Caută',
    new_quiz: 'Quiz nou',
    my_collections: 'Colecțiile mele',
    all_quizzes: 'Toate quiz-urile',
    new_folder: 'Folder nou',
    saved: 'Salvate',
    favorites: 'Favorite',
    history: 'Istoric',
    settings: 'Setări',
    profile: 'Profil',
    theme: 'Temă',
    language: 'Limbă',
    help: 'Ajutor',
    log_out: 'Deconectare',
    delete: 'Șterge',
    folder_name_placeholder: 'Nume folder',
    general_info: 'Informații generale',
    quiz_structure: 'Structura quiz-ului',
    settings_confirmation: 'Setări și confirmare',
    step_of: 'Pasul',
    of: 'din',
    quiz_name: 'Numele quiz-ului',
    quiz_name_placeholder: 'Biologie - Celula animală',
    description: 'Descriere',
    description_optional: 'opțional',
    description_placeholder: 'O scurtă descriere pentru participanți...',
    subject_category: 'Subiect / Categorie',
    choose_subject: 'Alege subiectul...',
    language_label: 'Limbă',
    visibility: 'Vizibilitate',
    public: 'Public',
    public_desc: 'Toți pot accesa',
    private: 'Privat',
    private_desc: 'Doar prin link',
    draft: 'Ciornă',
    draft_desc: 'Nu e vizibil public',
    num_questions: 'Număr de întrebări',
    between_1_100: 'Între 1 și 100',
    time_per_question: 'Timp pe întrebare',
    time_hint: '5 – 300 secunde',
    answer_choices: 'Variante de răspuns',
    choices_per_q: 'Variante pe întrebare:',
    question_type: 'Tipul întrebării',
    type_hint: 'poate fi schimbat per întrebare în editor',
    single_answer: 'Răspuns unic',
    single_desc: 'o variantă corectă',
    multiple_answers: 'Răspunsuri multiple',
    multiple_desc: 'mai multe variante corecte',
    true_false: 'Adevărat / Fals',
    true_false_desc: 'forțează 2 variante',
    behaviour: 'Comportament',
    question_order: 'Ordinea întrebărilor',
    answer_order: 'Ordinea răspunsurilor',
    fixed: 'Fixă',
    random: 'Aleatorie',
    allowed_attempts: 'Încercări permise',
    min_pass_score: 'Scor minim de promovare (%)',
    points_correct: 'Puncte per răspuns corect',
    display_options: 'Opțiuni de afișare',
    show_final_score: 'Afișează scorul final',
    correct_answers: 'Răspunsuri corecte',
    visible_timer: 'Timer vizibil',
    question_progress: 'Progres întrebări',
    allow_skip: 'Permite omiterea',
    summary: 'Sumar',
    back: 'Înapoi',
    cancel: 'Anulează',
    continue: 'Continuă',
    create_quiz: 'Creează quiz',
    creating: 'Se creează...',
    no_quizzes_title: 'Niciun quiz încă',
    no_quizzes_sub: 'Apasă Quiz nou pentru a crea primul.',
    my_quizzes_title: 'Quiz-urile mele',
    quiz_word: 'quiz',
    quizzes_word: 'quiz-uri',
    draft_label: 'Ciornă',
    published_label: 'Publicat',
    filled: 'completate',
    edit: 'Editează',
    daily_quiz: 'Quiz zilnic',
    trending: 'Populare săptămâna asta',
    recommended: 'Recomandate pentru tine',
    see_all: 'Vezi toate',
    show_less: 'Arată mai puțin',
    all: 'Toate',
    results_for: 'Rezultate pentru',
    found: 'găsite',
    no_quizzes_found: 'Niciun quiz găsit',
    no_quizzes_found_sub: 'Încearcă alt cuvânt cheie sau navighează pe categorii.',
    history_title: 'Istoric',
    no_history_title: 'Niciun istoric încă',
    no_history_sub: 'Quiz-urile jucate vor apărea aici',
    correct: 'corecte',
    notifications: 'Notificări',
    no_notifs_title: 'Nicio notificare încă',
    no_notifs_sub: 'Ești la zi!',
    notif_count: 'notificare',
    notifs_count: 'notificări',
    clear_all: 'Șterge toate',
    just_now: 'Chiar acum',
    ago: 'în urmă',
    mode: 'Mod',
    single_player: 'Jucător unic',
    single_player_desc: 'Exersează pe cont propriu',
    multiplayer: 'Multiplayer',
    multiplayer_desc: 'Joacă cu alții',
    save: 'Salvează',
    saved_label: 'Salvat',
    start_quiz: 'Începe quiz-ul',
    questions: 'Întrebări',
    time_per_q: 'Timp / întrebare',
    points_per_correct: 'Puncte / corect',
    pass_score: 'Scor promovare',
    add_question: 'Adaugă întrebare',
    question_text_placeholder: 'Scrie întrebarea aici...',
    time_sec: 'Timp (sec)',
    points: 'Puncte',
    type: 'Tip',
    single_type: 'Unic',
    multiple_type: 'Multiplu',
    true_false_type: 'Adevărat / Fals',
    answers_label: 'Răspunsuri',
    answers_hint: '(apasă iconița pentru a marca corect)',
    previous: 'Anterior',
    next: 'Următor',
    save_btn: 'Salvează',
    publish_quiz: 'Publică quiz-ul',
    no_folders: 'Niciun folder încă',
    get_ready: 'Pregătește-te!',
    almost: 'Aproape...',
    go: 'Start!',
    skip: 'Omite',
    times_up: 'Timpul a expirat!',
    incorrect: 'Incorect - răspuns corect:',
    see_results: 'Vezi rezultatele',
    perfect_score: 'Scor perfect!',
    quiz_passed: 'Quiz promovat!',
    keep_practicing: 'Continuă să exersezi!',
    scored_above: 'Ai obținut',
    above_pass: 'peste pragul de',
    pass_mark: 'promovare.',
    scored_below: 'Ai obținut',
    below_pass: 'pragul de promovare este',
    youve_got_this: 'Poți mai mult!',
    score: 'Scor',
    accuracy: 'Precizie',
    time: 'Timp',
    try_again: 'Încearcă din nou',
    back_to_quizzes: 'Înapoi la quiz-uri',
    profile_title: 'Profil',
    no_email: 'Fără email',
    help_title: 'Ajutor',
    help_1_title: 'Cum să începi',
    help_1_desc: 'Apasă Quiz nou pentru a crea primul quiz. Adaugă întrebări, setează un timer și publică.',
    help_2_title: 'Joacă un quiz',
    help_2_desc: 'Răsfoiește quiz-urile din Descoperă, apasă unul și pornește. Răspunde înainte să expire timerul.',
    help_3_title: 'Salvează quiz-uri',
    help_3_desc: 'Apasă iconița bookmark pe orice quiz pentru a-l salva la Favorite în sidebar.',
    help_4_title: 'Contact',
    help_4_desc: 'Contactează-ne pe Telegram sau Instagram — linkuri în footer-ul paginii principale.',
    toast_not_logged: 'Nu ești autentificat',
    toast_saved: 'Quiz salvat cu succes!',
    toast_published: 'a fost publicat cu succes.',
    toast_already_logged: 'Ești deja autentificat.',
    toast_daily_unavailable: 'Quiz-ul zilnic nu e disponibil',
    toast_login_to_create: 'Autentifică-te pentru a crea un quiz',
    delete_confirm: 'Ștergi?',
    yes: 'Da',
    no: 'Nu',
    start_now: 'Începe acum',
    max_questions_reached: 'Maximum 100 de întrebări atins',
    max_answers: 'Maximum 6 răspunsuri',
    add_answer: 'Adaugă răspuns',
    cat_mathematics: 'Matematică',
    cat_sciences: 'Științe',
    cat_history: 'Istorie',
    cat_geography: 'Geografie',
    cat_literature: 'Literatură',
    cat_technology: 'Tehnologie',
    cat_arts: 'Psihologie',
    cat_sports: 'Sport',
    cat_languages: 'Limbi',
    cat_general: 'Altele',
    trending_label: 'Populare',
    recommended_label: 'Recomandate pentru tine',
    summary_name: 'Nume',
    summary_subject: 'Subiect',
    summary_questions: 'Întrebări',
    summary_time_q: 'Timp / întrebare',
    summary_answer_choices: 'Variante răspuns',
    summary_visibility: 'Vizibilitate',
    summary_attempts: 'Încercări',
    summary_pass_score: 'Scor promovare',
    summary_points: 'Puncte / corect',
    summary_sec: 'sec.',
    editor_back: 'Înapoi',
    editor_add_question: 'Adaugă întrebare',
    editor_question_label: 'Textul întrebării',
    editor_answers_label: 'Răspunsuri',
    editor_answers_hint: '(apasă iconița pentru a marca corect)',
    editor_save: 'Salvează',
    editor_publish: 'Publică quiz-ul',
    editor_prev: 'Anterior',
    editor_next_q: 'Următor',
    editor_q_of: 'Întrebarea',
    editor_of: 'din',
    editor_option_single: 'Unic',
    editor_option_multiple: 'Multiplu',
    editor_option_truefalse: 'Adevărat / Fals',
    editor_add_answer: 'Adaugă răspuns',
    editor_max_answers: 'max',
    editor_no_folders: 'Niciun folder încă',
    editor_answer_placeholder: 'Răspuns',
    runner_next: 'Următor',
    runner_see_results: 'Vezi rezultatele',
    runner_correct_prefix: 'Corect! +',
    runner_correct_suffix: ' puncte',
    runner_q_of: 'Întrebarea',
    runner_of: 'din',
    info_questions: 'Întrebări',
    info_time_q: 'Timp / întrebare',
    info_points: 'Puncte / corect',
    info_pass: 'Scor promovare',
    contact: 'Contact',
    logout: 'Deconectare',
    contact_title:      'Contactează-ne',
    contact_sub:        'Îți răspundem cât mai curând posibil',
    contact_to_label:   'Către',
    contact_subj_label: 'Subiect',
    contact_subj_ph:    'Despre ce este vorba?',
    contact_msg_label:  'Mesaj',
    contact_msg_ph:     'Mesajul tău...',
    contact_send:       'Trimite mesaj',
    contact_sent:       'Mesaj trimis!',
    contact_socials:    'Sau contactează-ne pe rețele sociale',
  },
  ru: {
    home: 'Главная',
    my_quizzes: 'Мои тесты',
    discover: 'Узнай',
    search_placeholder: 'Поиск',
    new_quiz: 'Новый тест',
    my_collections: 'Мои коллекции',
    all_quizzes: 'Все тесты',
    new_folder: 'Новая папка',
    saved: 'Сохранённые',
    favorites: 'Избранное',
    history: 'История',
    settings: 'Настройки',
    profile: 'Профиль',
    theme: 'Тема',
    language: 'Язык',
    help: 'Помощь',
    log_out: 'Выйти',
    delete: 'Удалить',
    folder_name_placeholder: 'Название папки',
    general_info: 'Общая информация',
    quiz_structure: 'Структура теста',
    settings_confirmation: 'Настройки и подтверждение',
    step_of: 'Шаг',
    of: 'из',
    quiz_name: 'Название теста',
    quiz_name_placeholder: 'Биология - Клетка животного',
    description: 'Описание',
    description_optional: 'необязательно',
    description_placeholder: 'Краткое описание для участников...',
    subject_category: 'Предмет / Категория',
    choose_subject: 'Выберите предмет...',
    language_label: 'Язык',
    visibility: 'Видимость',
    public: 'Публичный',
    public_desc: 'Доступен всем',
    private: 'Приватный',
    private_desc: 'Только по ссылке',
    draft: 'Черновик',
    draft_desc: 'Не виден публично',
    num_questions: 'Количество вопросов',
    between_1_100: 'От 1 до 100',
    time_per_question: 'Время на вопрос',
    time_hint: '5 – 300 секунд',
    answer_choices: 'Варианты ответов',
    choices_per_q: 'Вариантов на вопрос:',
    question_type: 'Тип вопроса',
    type_hint: 'можно изменить для каждого вопроса в редакторе',
    single_answer: 'Один ответ',
    single_desc: 'один правильный вариант',
    multiple_answers: 'Несколько ответов',
    multiple_desc: 'несколько правильных вариантов',
    true_false: 'Верно / Неверно',
    true_false_desc: 'принудительно 2 варианта',
    behaviour: 'Поведение',
    question_order: 'Порядок вопросов',
    answer_order: 'Порядок ответов',
    fixed: 'Фиксированный',
    random: 'Случайный',
    allowed_attempts: 'Разрешённых попыток',
    min_pass_score: 'Минимальный проходной балл (%)',
    points_correct: 'Баллов за правильный ответ',
    display_options: 'Параметры отображения',
    show_final_score: 'Показать итоговый балл',
    correct_answers: 'Правильные ответы',
    visible_timer: 'Видимый таймер',
    question_progress: 'Прогресс вопросов',
    allow_skip: 'Разрешить пропуск',
    summary: 'Сводка',
    back: 'Назад',
    cancel: 'Отмена',
    continue: 'Продолжить',
    create_quiz: 'Создать тест',
    creating: 'Создание...',
    no_quizzes_title: 'Тестов пока нет',
    no_quizzes_sub: 'Нажмите Новый тест, чтобы создать первый.',
    my_quizzes_title: 'Мои тесты',
    quiz_word: 'тест',
    quizzes_word: 'тестов',
    draft_label: 'Черновик',
    published_label: 'Опубликован',
    filled: 'заполнено',
    edit: 'Изменить',
    daily_quiz: 'Тест дня',
    trending: 'Популярное на этой неделе',
    recommended: 'Рекомендуем для вас',
    see_all: 'Смотреть все',
    show_less: 'Свернуть',
    all: 'Все',
    results_for: 'Результаты для',
    found: 'найдено',
    no_quizzes_found: 'Тесты не найдены',
    no_quizzes_found_sub: 'Попробуйте другое слово или просмотрите категории.',
    history_title: 'История',
    no_history_title: 'Истории пока нет',
    no_history_sub: 'Пройденные тесты появятся здесь',
    correct: 'правильно',
    notifications: 'Уведомления',
    no_notifs_title: 'Уведомлений пока нет',
    no_notifs_sub: 'Всё актуально!',
    notif_count: 'уведомление',
    notifs_count: 'уведомлений',
    clear_all: 'Очистить все',
    just_now: 'Только что',
    ago: 'назад',
    mode: 'Режим',
    single_player: 'Одиночная игра',
    single_player_desc: 'Практикуйтесь самостоятельно',
    multiplayer: 'Мультиплеер',
    multiplayer_desc: 'Играйте с другими',
    save: 'Сохранить',
    saved_label: 'Сохранено',
    start_quiz: 'Начать тест',
    questions: 'Вопросы',
    time_per_q: 'Время / вопрос',
    points_per_correct: 'Баллы / правильно',
    pass_score: 'Проходной балл',
    add_question: 'Добавить вопрос',
    question_text_placeholder: 'Введите вопрос здесь...',
    time_sec: 'Время (сек)',
    points: 'Баллы',
    type: 'Тип',
    single_type: 'Один',
    multiple_type: 'Несколько',
    true_false_type: 'Верно / Неверно',
    answers_label: 'Ответы',
    answers_hint: '(нажмите иконку, чтобы отметить правильный)',
    previous: 'Назад',
    next: 'Далее',
    save_btn: 'Сохранить',
    publish_quiz: 'Опубликовать тест',
    no_folders: 'Папок пока нет',
    get_ready: 'Приготовьтесь!',
    almost: 'Почти...',
    go: 'Вперёд!',
    skip: 'Пропустить',
    times_up: 'Время вышло!',
    incorrect: 'Неверно - правильный ответ:',
    see_results: 'Смотреть результаты',
    perfect_score: 'Идеальный результат!',
    quiz_passed: 'Тест пройден!',
    keep_practicing: 'Продолжайте практиковаться!',
    scored_above: 'Вы набрали',
    above_pass: 'выше порога',
    pass_mark: 'прохождения.',
    scored_below: 'Вы набрали',
    below_pass: 'проходной балл —',
    youve_got_this: 'У вас получится!',
    score: 'Счёт',
    accuracy: 'Точность',
    time: 'Время',
    try_again: 'Попробовать снова',
    back_to_quizzes: 'Назад к тестам',
    profile_title: 'Профиль',
    no_email: 'Без email',
    help_title: 'Помощь',
    help_1_title: 'Начало работы',
    help_1_desc: 'Нажмите Новый тест, чтобы создать первый тест. Добавьте вопросы, установите таймер и опубликуйте.',
    help_2_title: 'Прохождение теста',
    help_2_desc: 'Просмотрите тесты в разделе Открыть, выберите один и нажмите Начать тест. Отвечайте до истечения таймера.',
    help_3_title: 'Сохранение тестов',
    help_3_desc: 'Нажмите значок закладки на любом тесте, чтобы сохранить его в Избранное на боковой панели.',
    help_4_title: 'Контакты',
    help_4_desc: 'Напишите нам в Telegram или Instagram — ссылки в подвале главной страницы.',
    toast_not_logged: 'Вы не авторизованы',
    toast_saved: 'Тест успешно сохранён!',
    toast_published: 'успешно опубликован.',
    toast_already_logged: 'Вы уже авторизованы.',
    toast_daily_unavailable: 'Тест дня недоступен',
    toast_login_to_create: 'Войдите, чтобы создать тест',
    delete_confirm: 'Удалить?',
    yes: 'Да',
    no: 'Нет',
    start_now: 'Начать сейчас',
    max_questions_reached: 'Достигнут максимум 100 вопросов',
    max_answers: 'Максимум 6 ответов',
    add_answer: 'Добавить ответ',
    cat_mathematics: 'Математика',
    cat_sciences: 'Науки',
    cat_history: 'История',
    cat_geography: 'География',
    cat_literature: 'Литература',
    cat_technology: 'Технологии',
    cat_arts: 'Психология',
    cat_sports: 'Спорт',
    cat_languages: 'Языки',
    cat_general: 'Другие',
    trending_label: 'Популярное',
    recommended_label: 'Рекомендуем для вас',
    summary_name: 'Название',
    summary_subject: 'Предмет',
    summary_questions: 'Вопросы',
    summary_time_q: 'Время / вопрос',
    summary_answer_choices: 'Вариантов ответа',
    summary_visibility: 'Видимость',
    summary_attempts: 'Попытки',
    summary_pass_score: 'Проходной балл',
    summary_points: 'Баллы / правильно',
    summary_sec: 'сек.',
    editor_back: 'Назад',
    editor_add_question: 'Добавить вопрос',
    editor_question_label: 'Текст вопроса',
    editor_answers_label: 'Ответы',
    editor_answers_hint: '(нажмите иконку, чтобы отметить правильный)',
    editor_save: 'Сохранить',
    editor_publish: 'Опубликовать тест',
    editor_prev: 'Назад',
    editor_next_q: 'Далее',
    editor_q_of: 'Вопрос',
    editor_of: 'из',
    editor_option_single: 'Один',
    editor_option_multiple: 'Несколько',
    editor_option_truefalse: 'Верно / Неверно',
    editor_add_answer: 'Добавить ответ',
    editor_max_answers: 'макс',
    editor_no_folders: 'Папок пока нет',
    editor_answer_placeholder: 'Ответ',
    runner_next: 'Далее',
    runner_see_results: 'Смотреть результаты',
    runner_correct_prefix: 'Верно! +',
    runner_correct_suffix: ' баллов',
    runner_q_of: 'Вопрос',
    runner_of: 'из',
    info_questions: 'Вопросы',
    info_time_q: 'Время / вопрос',
    info_points: 'Баллы / правильно',
    info_pass: 'Проходной балл',
    contact: 'Контакт',
    logout: 'Выйти',
    contact_title:      'Связаться с нами',
    contact_sub:        'Мы ответим как можно скорее',
    contact_to_label:   'Кому',
    contact_subj_label: 'Тема',
    contact_subj_ph:    'О чём это?',
    contact_msg_label:  'Сообщение',
    contact_msg_ph:     'Ваше сообщение...',
    contact_send:       'Отправить сообщение',
    contact_sent:       'Сообщение отправлено!',
    contact_socials:    'Или напишите в соцсетях',
  }
};

function t(key) {
  const lang = localStorage.getItem('blitziq-lang') || 'en';
  return (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) || TRANSLATIONS.en[key] || key;
}

function applyTranslations() {
  const lang = localStorage.getItem('blitziq-lang') || 'en';

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    const val = t(key);
    if (val) el.textContent = val;
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    const val = t(key);
    if (val) el.placeholder = val;
  });

  if (typeof renderMyQuizzes === 'function') renderMyQuizzes();
  if (typeof renderFolders === 'function') renderFolders();
  if (typeof renderNotifications === 'function') renderNotifications();
  if (typeof renderHistory === 'function') renderHistory();
  if (typeof renderDiscoverCategories === 'function') renderDiscoverCategories();
  const homeRoot = document.getElementById('home-features-root');
  if (homeRoot) homeRoot.remove();
  if (typeof renderHomeFeatures === 'function') renderHomeFeatures();
}

window.applyTranslations = applyTranslations;