const TRANSLATIONS_L = {
  en: {
    nav_home:        'Home',
    nav_features:    'Features',
    nav_demo:        'Demo',
    nav_about:       'About',
    nav_contact:     'Contact',
    nav_login:       'Log in',
    nav_signup:      'Sign up',
    nav_logout:      'Log out',
    hero_title:      'The fastest way to<br>run live quizzes',
    hero_sub:        'Your crowd. Your questions.',
    hero_desc:       'Create, share, and host real-time quizzes - for classrooms, events, or just for fun.',
    hero_start:      'Start creating',
    hero_try:        'Try a quiz',
    hero_join_title: 'Try it now',
    hero_join_ph:    'Code',
    hero_join_btn:   'Join',
    features_heading:  "Everything you need.<br><span>Nothing you don't.</span>",
    feat1_title:  'Build a quiz in under a minute',
    feat1_desc:   'Type your questions, pick the right answer, set a timer. No learning curve, just a clean editor that gets out of your way.',
    feat2_title:  'Timed pressure',
    feat2_desc:   'Every question has a countdown. Fast answers score more.',
    feat2_sec:    'seconds left',
    feat3_title:  'Results after every session',
    feat3_desc:   'See which questions people skipped the most and their percentage.',
    feat3_players:   'players',
    feat3_avg:       'avg score',
    feat3_questions: 'questions',
    game_badge:         'Interactive',
    game_next_q:        'Next question',
    game_try_again:     'Try again',
    game_start_title:   'PHP Quiz',
    game_start_desc:    '3 questions · 15 seconds each<br>Test your PHP knowledge',
    game_start_btn:     'Start quiz',
    game_q_of:          'Question',
    game_of:            'of',
    game_times_up:      "Time's up! ",
    game_result_0_title: 'Keep practicing!',
    game_result_1_title: 'Good start!',
    game_result_2_title: 'PHP Master!',
    game_result_0_sub:   'PHP has many quirks. Review the docs and give it another shot!',
    game_result_1_sub:   "You're getting there - a bit more practice and you'll nail it.",
    game_result_2_sub:   'You know type juggling, security & breaking changes. Impressive!',
    about_heading:  'Built for speed.<br><span>Designed for everyone.</span>',
    about1_title: 'Create in seconds',
    about1_desc:  'Add your questions, set the timer and you\'re ready. No complicated setup, no learning curve.',
    about2_title: 'Play live with anyone',
    about2_desc:  'Share a simple code and participants join instantly from any device, anywhere.',
    about3_title: 'Multiple choice questions',
    about3_desc:  '4 answer options, one correct. Simple for players, efficient for the host.',
    about4_title: 'Detailed analytics',
    about4_desc:  'See which questions were hardest and how well your group performed after each session.',
    about5_title: 'For any occasion',
    about5_desc:  'Classroom, team building, party or event, Blitziq adapts to your context.',
    about6_title: 'Free to start',
    about6_desc:  'Create your account and launch your first quiz in less than 2 minutes. No credit card needed.',
    cta_title:   'Ready to run your first quiz?',
    cta_desc:    'Join thousands of hosts already using Blitziq, free to start, no card needed.',
    cta_signup:  'Create account',
    cta_contact: 'Talk to us',
    footer_desc:         'The interactive quiz platform that makes learning captivating for students and professionals alike.',
    footer_product:      'Product',
    footer_features:     'Features',
    footer_demo:         'Demo game',
    footer_about:        'About',
    footer_contact:      'Contact',
    footer_company:      'Company',
    footer_contacts:     'Contacts',
    footer_terms:        'Terms & Conditions',
    footer_privacy:      'Privacy Policy',
    footer_socials:      'Socials',
    footer_copy:         '© 2026 Blitziq',
    login_title:         'Welcome back',
    login_sub:           'Log in to your account',
    login_email_label:   'Email or username',
    login_email_ph:      'you@example.com',
    login_pass_label:    'Password',
    login_pass_ph:       '••••••••',
    login_btn:           'Log in',
    login_switch:        "Don't have an account?",
    login_switch_btn:    'Sign up',
    signup_title:        'Create account',
    signup_sub:          'Join thousands of quiz creators',
    signup_user_label:   'Username',
    signup_user_ph:      'coolquizmaster',
    signup_email_label:  'Email',
    signup_email_ph:     'you@example.com',
    signup_pass_label:   'Password',
    signup_pass_ph:      'Min. 8 characters',
    signup_confirm_label:'Confirm password',
    signup_confirm_ph:   'Repeat password',
    signup_btn:          'Create account',
    signup_switch:       'Already have an account?',
    signup_switch_btn:   'Log in',
    contact_title:       'Get in touch',
    contact_sub:         "We'll get back to you as soon as possible",
    contact_to_label:    'To',
    contact_subj_label:  'Subject',
    contact_subj_ph:     "What's this about?",
    contact_msg_label:   'Message',
    contact_msg_ph:      'Your message...',
    contact_send:        'Send message',
    contact_sent:        'Message sent!',
    contact_socials:     'Or reach out on socials',
    contact_login_pre:   'to send a message directly.',
    contact_login_link:  'Log in',
    about_ov_title:      'About BlitzIQ',
    about_ov_q_label:    'What is BlitzIQ?',
    about_ov_q_text:     'BlitzIQ is a live quiz platform. A question appears, a timer counts down, you answer fast. Simple to host, instant to join, built for classrooms, events, or anyone who thinks learning should feel like a game.',
    about_ov_score_label:'How scoring works',
    about_ov_score_text: 'Every correct answer scores points. Answer faster and you score <strong>more</strong> - the timer is part of the game. Wrong or late answers score zero. Final rankings are shown after the last question.',
    about_ov_types_label:'Question types',
    about_ov_types_text: 'Multiple choice with up to <strong>6 options</strong>, true/false, and timed open questions. Each quiz supports up to <strong>100 questions</strong>, with per-question time limits from 5 to 300 seconds.',
    about_ov_built:      'Built by Culbida Mihail',
    about_ov_create:     'Start creating',
    terms_title:         'Terms & Conditions',
    terms_using_label:   'Using the platform',
    terms_using_text:    'BlitzIQ is open to anyone aged <strong>13 or older</strong>. Use is permitted for personal, non-commercial purposes only. We reserve the right to suspend any account without prior notice if these terms are violated.',
    terms_ip_label:      'Intellectual property',
    terms_ip_text:       'The interface, logo, code, and all other elements of the platform are protected by copyright and belong to BlitzIQ. Content created by users - questions, answers, quizzes, remains their property. Reproducing or distributing platform elements without written permission is prohibited.',
    terms_liab_label:    'Liability',
    terms_liab_text:     'BlitzIQ is provided without guarantees of uninterrupted availability or data accuracy. The owner cannot be held liable for data loss, service interruptions, or any damages resulting from the use of the platform.',
    terms_conduct_label: 'Conduct',
    terms_conduct_text:  'Publishing content that is illegal, misleading, or harmful to others is strictly prohibited. Attempts to copy, reverse-engineer, or exploit the platform, as well as any automated use that disrupts normal service - are not permitted.',
    terms_accept:        'Got it',
    privacy_title:       'Privacy Policy',
    privacy_collect_label:'What we collect',
    privacy_collect_text: 'When you create an account, we store your <strong>username</strong> and <strong>email address</strong>. When you create or play a quiz, we store the content and results associated with your account. We do not collect payment information, location data, or any data beyond what is necessary to run the platform.',
    privacy_use_label:   'How we use it',
    privacy_use_text:    'Your data is used solely to provide and improve the BlitzIQ service - account authentication, displaying your quizzes, and showing session results. We do not sell, rent, or share your personal data with third parties for marketing purposes.',
    privacy_cookies_label:'Cookies',
    privacy_cookies_text: 'BlitzIQ uses a single session cookie to keep you logged in. No tracking cookies, no analytics cookies, no third-party advertising scripts. The session cookie is deleted when you log out or close the browser.',
    privacy_rights_label: 'Your rights',
    privacy_rights_text:  'You can request the deletion of your account and all associated data at any time by contacting us directly. We will process the request within a reasonable timeframe and confirm once complete.',
    privacy_accept:      'Got it',
    toast_not_logged:    'You are not logged in',
    toast_already_logged:'You are already logged in.',
    error_network:       'Network error, please try again.',
    error_generic:       'Something went wrong.',
    nav_theme: 'Theme',
  },

  ro: {
    nav_home:        'Acasă',
    nav_features:    'Funcții',
    nav_demo:        'Demo',
    nav_about:       'Despre',
    nav_contact:     'Contact',
    nav_login:       'Autentificare',
    nav_signup:      'Înregistrare',
    nav_logout:      'Deconectare',
    hero_title:      'Cel mai rapid mod de<br>a crea quiz-uri live',
    hero_sub:        'Publicul tău. Întrebările tale.',
    hero_desc:       'Creează, distribuie și găzduiește quiz-uri în timp real — pentru clase, evenimente sau pur și simplu pentru distracție.',
    hero_start:      'Începe să creezi',
    hero_try:        'Încearcă un quiz',
    hero_join_title: 'Încearcă acum',
    hero_join_ph:    'Cod',
    hero_join_btn:   'Intră',
    features_heading:  'Tot ce ai nevoie.<br><span>Nimic în plus.</span>',
    feat1_title:  'Creează un quiz în mai puțin de un minut',
    feat1_desc:   'Scrie întrebările, alege răspunsul corect, setează un timer. Fără curbă de învățare, doar un editor curat.',
    feat2_title:  'Presiunea timpului',
    feat2_desc:   'Fiecare întrebare are un cronometru. Răspunsurile rapide aduc mai multe puncte.',
    feat2_sec:    'secunde rămase',
    feat3_title:  'Rezultate după fiecare sesiune',
    feat3_desc:   'Vezi ce întrebări au fost omise cel mai des și procentajul lor.',
    feat3_players:   'jucători',
    feat3_avg:       'scor mediu',
    feat3_questions: 'întrebări',
    game_badge:         'Interactiv',
    game_next_q:        'Întrebarea următoare',
    game_try_again:     'Încearcă din nou',
    game_start_title:   'Quiz PHP',
    game_start_desc:    '3 întrebări · 15 secunde fiecare<br>Testează-ți cunoștințele de PHP',
    game_start_btn:     'Începe quiz-ul',
    game_q_of:          'Întrebarea',
    game_of:            'din',
    game_times_up:      'Timpul a expirat! ',
    game_result_0_title: 'Continuă să exersezi!',
    game_result_1_title: 'Start bun!',
    game_result_2_title: 'Maestru PHP!',
    game_result_0_sub:   'PHP are multe capcane. Revizuiește documentația și mai încearcă o dată!',
    game_result_1_sub:   'Ești pe drumul cel bun — mai puțin antrenament și vei reuși.',
    game_result_2_sub:   'Știi type juggling, securitate și modificări de versiune. Impresionant!',
    about_heading:  'Construit pentru viteză.<br><span>Proiectat pentru toți.</span>',
    about1_title: 'Creează în secunde',
    about1_desc:  'Adaugă întrebările, setează timerul și ești gata. Nicio configurare complicată.',
    about2_title: 'Joacă live cu oricine',
    about2_desc:  'Distribuie un cod simplu și participanții se alătură instant de pe orice dispozitiv.',
    about3_title: 'Întrebări cu variante multiple',
    about3_desc:  '4 opțiuni de răspuns, una corectă. Simplu pentru jucători, eficient pentru gazdă.',
    about4_title: 'Analize detaliate',
    about4_desc:  'Vezi ce întrebări au fost cele mai grele și cum a performat grupul tău.',
    about5_title: 'Pentru orice ocazie',
    about5_desc:  'Clasă, team building, petrecere sau eveniment — Blitziq se adaptează contextului.',
    about6_title: 'Gratuit pentru start',
    about6_desc:  'Creează-ți contul și lansează primul quiz în mai puțin de 2 minute. Fără card bancar.',
    cta_title:   'Gata să rulezi primul tău quiz?',
    cta_desc:    'Alătură-te miilor de gazde care folosesc deja Blitziq, gratuit, fără card.',
    cta_signup:  'Creează cont',
    cta_contact: 'Contactează-ne',
    footer_desc:         'Platforma interactivă de quiz-uri care face învățarea captivantă pentru elevi și profesioniști.',
    footer_product:      'Produs',
    footer_features:     'Funcții',
    footer_demo:         'Demo',
    footer_about:        'Despre',
    footer_contact:      'Contact',
    footer_company:      'Companie',
    footer_contacts:     'Contacte',
    footer_terms:        'Termeni și condiții',
    footer_privacy:      'Politica de confidențialitate',
    footer_socials:      'Rețele sociale',
    footer_copy:         '© 2026 Blitziq',
    login_title:         'Bine ai revenit',
    login_sub:           'Autentifică-te în cont',
    login_email_label:   'Email sau nume de utilizator',
    login_email_ph:      'tu@exemplu.com',
    login_pass_label:    'Parolă',
    login_pass_ph:       '••••••••',
    login_btn:           'Autentificare',
    login_switch:        'Nu ai cont?',
    login_switch_btn:    'Înregistrează-te',
    signup_title:        'Creează cont',
    signup_sub:          'Alătură-te miilor de creatori de quiz-uri',
    signup_user_label:   'Nume de utilizator',
    signup_user_ph:      'maestrulquizurilor',
    signup_email_label:  'Email',
    signup_email_ph:     'tu@exemplu.com',
    signup_pass_label:   'Parolă',
    signup_pass_ph:      'Min. 8 caractere',
    signup_confirm_label:'Confirmă parola',
    signup_confirm_ph:   'Repetă parola',
    signup_btn:          'Creează cont',
    signup_switch:       'Ai deja un cont?',
    signup_switch_btn:   'Autentifică-te',
    contact_title:       'Contactează-ne',
    contact_sub:         'Îți răspundem cât mai curând posibil',
    contact_to_label:    'Către',
    contact_subj_label:  'Subiect',
    contact_subj_ph:     'Despre ce este vorba?',
    contact_msg_label:   'Mesaj',
    contact_msg_ph:      'Mesajul tău...',
    contact_send:        'Trimite mesaj',
    contact_sent:        'Mesaj trimis!',
    contact_socials:     'Sau contactează-ne pe rețele sociale',
    contact_login_pre:   'pentru a trimite un mesaj direct.',
    contact_login_link:  'Autentifică-te',
    about_ov_title:      'Despre BlitzIQ',
    about_ov_q_label:    'Ce este BlitzIQ?',
    about_ov_q_text:     'BlitzIQ este o platformă de quiz-uri live. Apare o întrebare, un cronometru numără invers, răspunzi rapid. Simplu de găzduit, instant de accesat, construit pentru clase, evenimente sau pentru oricine crede că învățarea trebuie să semene cu un joc.',
    about_ov_score_label:'Cum funcționează punctajul',
    about_ov_score_text: 'Fiecare răspuns corect aduce puncte. Răspunde mai repede și vei obține <strong>mai mult</strong> — cronometrul face parte din joc. Răspunsurile greșite sau tardive nu aduc puncte. Clasamentul final se afișează după ultima întrebare.',
    about_ov_types_label:'Tipuri de întrebări',
    about_ov_types_text: 'Alegere multiplă cu până la <strong>6 opțiuni</strong>, adevărat/fals și întrebări deschise cronometrate. Fiecare quiz suportă până la <strong>100 de întrebări</strong>, cu limite de timp per întrebare de la 5 la 300 de secunde.',
    about_ov_built:      'Creat de Culbida Mihail',
    about_ov_create:     'Începe să creezi',
    terms_title:         'Termeni și condiții',
    terms_using_label:   'Utilizarea platformei',
    terms_using_text:    'BlitzIQ este disponibil pentru oricine de <strong>13 ani sau mai mult</strong>. Utilizarea este permisă exclusiv în scopuri personale, necomerciale. Ne rezervăm dreptul de a suspenda orice cont fără notificare prealabilă dacă acești termeni sunt încălcați.',
    terms_ip_label:      'Proprietate intelectuală',
    terms_ip_text:       'Interfața, logo-ul, codul și toate celelalte elemente ale platformei sunt protejate de dreptul de autor și aparțin BlitzIQ. Conținutul creat de utilizatori — întrebări, răspunsuri, quiz-uri — rămâne proprietatea acestora. Reproducerea sau distribuirea elementelor platformei fără permisiune scrisă este interzisă.',
    terms_liab_label:    'Răspundere',
    terms_liab_text:     'BlitzIQ este furnizat fără garanții privind disponibilitatea neîntreruptă sau acuratețea datelor. Proprietarul nu poate fi tras la răspundere pentru pierderi de date, întreruperi de serviciu sau orice daune rezultate din utilizarea platformei.',
    terms_conduct_label: 'Conduită',
    terms_conduct_text:  'Publicarea conținutului ilegal, înșelător sau dăunător pentru alții este strict interzisă. Tentativele de copiere, inginerie inversă sau exploatare a platformei, precum și orice utilizare automată care perturbă serviciul normal — nu sunt permise.',
    terms_accept:        'Am înțeles',
    privacy_title:       'Politica de confidențialitate',
    privacy_collect_label:'Ce colectăm',
    privacy_collect_text: 'Când îți creezi contul, stocăm <strong>numele de utilizator</strong> și <strong>adresa de email</strong>. Când creezi sau joci un quiz, stocăm conținutul și rezultatele asociate contului. Nu colectăm informații de plată, date de localizare sau orice date dincolo de ceea ce este necesar pentru funcționarea platformei.',
    privacy_use_label:   'Cum le folosim',
    privacy_use_text:    'Datele tale sunt utilizate exclusiv pentru a furniza și îmbunătăți serviciul BlitzIQ — autentificarea în cont, afișarea quiz-urilor tale și prezentarea rezultatelor sesiunilor. Nu vindem, nu închiriem și nu partajăm datele tale personale cu terți în scopuri de marketing.',
    privacy_cookies_label:'Cookie-uri',
    privacy_cookies_text: 'BlitzIQ folosește un singur cookie de sesiune pentru a te menține autentificat. Fără cookie-uri de urmărire, fără cookie-uri de analiză, fără scripturi publicitare terțe. Cookie-ul de sesiune este șters când te deconectezi sau închizi browserul.',
    privacy_rights_label: 'Drepturile tale',
    privacy_rights_text:  'Poți solicita ștergerea contului și a tuturor datelor asociate oricând, contactându-ne direct. Vom procesa solicitarea într-un termen rezonabil și vom confirma finalizarea.',
    privacy_accept:      'Am înțeles',
    toast_not_logged:    'Nu ești autentificat',
    toast_already_logged:'Ești deja autentificat.',
    error_network:       'Eroare de rețea, încearcă din nou.',
    error_generic:       'Ceva a mers greșit.',
    nav_theme: 'Temă',
  },

  ru: {
    nav_home:        'Главная',
    nav_features:    'Функции',
    nav_demo:        'Демо',
    nav_about:       'О нас',
    nav_contact:     'Контакт',
    nav_login:       'Войти',
    nav_signup:      'Регистрация',
    nav_logout:      'Выйти',
    hero_title:      'Самый быстрый способ<br>проводить живые тесты',
    hero_sub:        'Ваша аудитория. Ваши вопросы.',
    hero_desc:       'Создавайте, делитесь и проводите тесты в реальном времени — для классов, мероприятий или просто для удовольствия.',
    hero_start:      'Начать создавать',
    hero_try:        'Попробовать тест',
    hero_join_title: 'Попробуйте сейчас',
    hero_join_ph:    'Код',
    hero_join_btn:   'Войти',
    features_heading:  'Всё необходимое.<br><span>Ничего лишнего.</span>',
    feat1_title:  'Создайте тест менее чем за минуту',
    feat1_desc:   'Напишите вопросы, выберите правильный ответ, задайте таймер. Никакой кривой обучения — только чистый редактор.',
    feat2_title:  'Давление времени',
    feat2_desc:   'У каждого вопроса есть обратный отсчёт. Быстрые ответы приносят больше очков.',
    feat2_sec:    'секунд осталось',
    feat3_title:  'Результаты после каждой сессии',
    feat3_desc:   'Смотрите, какие вопросы пропускали чаще всего и их процентаж.',
    feat3_players:   'игроков',
    feat3_avg:       'средний балл',
    feat3_questions: 'вопросов',
    game_badge:         'Интерактивно',
    game_next_q:        'Следующий вопрос',
    game_try_again:     'Попробовать снова',
    game_start_title:   'PHP-тест',
    game_start_desc:    '3 вопроса · 15 секунд каждый<br>Проверьте знания PHP',
    game_start_btn:     'Начать тест',
    game_q_of:          'Вопрос',
    game_of:            'из',
    game_times_up:      'Время вышло! ',
    game_result_0_title: 'Продолжайте практиковаться!',
    game_result_1_title: 'Хорошее начало!',
    game_result_2_title: 'Мастер PHP!',
    game_result_0_sub:   'PHP полон тонкостей. Изучите документацию и попробуйте ещё раз!',
    game_result_1_sub:   'Вы на правильном пути — ещё немного практики, и вы всё освоите.',
    game_result_2_sub:   'Вы знаете жонглирование типами, безопасность и изменения версий. Впечатляет!',
    about_heading:  'Создан для скорости.<br><span>Разработан для всех.</span>',
    about1_title: 'Создавайте за секунды',
    about1_desc:  'Добавьте вопросы, установите таймер — и вы готовы. Никакой сложной настройки.',
    about2_title: 'Играйте вживую с кем угодно',
    about2_desc:  'Поделитесь простым кодом, и участники мгновенно присоединятся с любого устройства.',
    about3_title: 'Вопросы с несколькими вариантами',
    about3_desc:  '4 варианта ответа, один правильный. Просто для игроков, удобно для ведущего.',
    about4_title: 'Детальная аналитика',
    about4_desc:  'Узнайте, какие вопросы были сложнейшими и как справилась ваша группа.',
    about5_title: 'Для любого случая',
    about5_desc:  'Класс, тимбилдинг, вечеринка или мероприятие — Blitziq адаптируется к контексту.',
    about6_title: 'Бесплатный старт',
    about6_desc:  'Создайте аккаунт и запустите первый тест менее чем за 2 минуты. Банковская карта не нужна.',
    cta_title:   'Готовы провести первый тест?',
    cta_desc:    'Присоединяйтесь к тысячам ведущих, уже использующих Blitziq — бесплатно, без карты.',
    cta_signup:  'Создать аккаунт',
    cta_contact: 'Написать нам',
    footer_desc:         'Интерактивная платформа тестов, делающая обучение увлекательным для учеников и профессионалов.',
    footer_product:      'Продукт',
    footer_features:     'Функции',
    footer_demo:         'Демо',
    footer_about:        'О нас',
    footer_contact:      'Контакт',
    footer_company:      'Компания',
    footer_contacts:     'Контакты',
    footer_terms:        'Условия использования',
    footer_privacy:      'Политика конфиденциальности',
    footer_socials:      'Соцсети',
    footer_copy:         '© 2026 Blitziq',
    login_title:         'С возвращением',
    login_sub:           'Войдите в свой аккаунт',
    login_email_label:   'Email или имя пользователя',
    login_email_ph:      'you@example.com',
    login_pass_label:    'Пароль',
    login_pass_ph:       '••••••••',
    login_btn:           'Войти',
    login_switch:        'Нет аккаунта?',
    login_switch_btn:    'Зарегистрироваться',
    signup_title:        'Создать аккаунт',
    signup_sub:          'Присоединяйтесь к тысячам создателей тестов',
    signup_user_label:   'Имя пользователя',
    signup_user_ph:      'мастертестов',
    signup_email_label:  'Email',
    signup_email_ph:     'you@example.com',
    signup_pass_label:   'Пароль',
    signup_pass_ph:      'Мин. 8 символов',
    signup_confirm_label:'Подтвердите пароль',
    signup_confirm_ph:   'Повторите пароль',
    signup_btn:          'Создать аккаунт',
    signup_switch:       'Уже есть аккаунт?',
    signup_switch_btn:   'Войти',
    contact_title:       'Связаться с нами',
    contact_sub:         'Мы ответим как можно скорее',
    contact_to_label:    'Кому',
    contact_subj_label:  'Тема',
    contact_subj_ph:     'О чём это?',
    contact_msg_label:   'Сообщение',
    contact_msg_ph:      'Ваше сообщение...',
    contact_send:        'Отправить сообщение',
    contact_sent:        'Сообщение отправлено!',
    contact_socials:     'Или напишите в соцсетях',
    contact_login_pre:   'чтобы отправить сообщение напрямую.',
    contact_login_link:  'Войдите',
    about_ov_title:      'О BlitzIQ',
    about_ov_q_label:    'Что такое BlitzIQ?',
    about_ov_q_text:     'BlitzIQ — живая платформа для тестов. Появляется вопрос, идёт обратный отсчёт, вы отвечаете быстро. Легко вести, мгновенно присоединиться — создано для классов, мероприятий или всех, кто считает, что обучение должно быть похоже на игру.',
    about_ov_score_label:'Как работает подсчёт очков',
    about_ov_score_text: 'Каждый правильный ответ приносит очки. Отвечайте быстрее — получайте <strong>больше</strong>, таймер — часть игры. Неверные или поздние ответы дают ноль. Итоговый рейтинг показывается после последнего вопроса.',
    about_ov_types_label:'Типы вопросов',
    about_ov_types_text: 'Множественный выбор до <strong>6 вариантов</strong>, верно/неверно и вопросы с открытым ответом. Каждый тест поддерживает до <strong>100 вопросов</strong>, с лимитами по времени от 5 до 300 секунд.',
    about_ov_built:      'Создано Кулбидой Михаилом',
    about_ov_create:     'Начать создавать',
    terms_title:         'Условия использования',
    terms_using_label:   'Использование платформы',
    terms_using_text:    'BlitzIQ открыт для всех, кому <strong>13 лет и старше</strong>. Использование разрешено только в личных, некоммерческих целях. Мы оставляем за собой право приостановить любой аккаунт без предварительного уведомления при нарушении этих условий.',
    terms_ip_label:      'Интеллектуальная собственность',
    terms_ip_text:       'Интерфейс, логотип, код и все другие элементы платформы защищены авторским правом и принадлежат BlitzIQ. Контент, созданный пользователями — вопросы, ответы, тесты — остаётся их собственностью. Воспроизведение или распространение элементов платформы без письменного разрешения запрещено.',
    terms_liab_label:    'Ответственность',
    terms_liab_text:     'BlitzIQ предоставляется без гарантий непрерывной доступности или точности данных. Владелец не несёт ответственности за потерю данных, перебои в работе или любой ущерб, возникший в результате использования платформы.',
    terms_conduct_label: 'Поведение',
    terms_conduct_text:  'Публикация незаконного, вводящего в заблуждение или вредоносного контента строго запрещена. Попытки копировать, реверс-инжиниринг или эксплуатировать платформу, а также любое автоматическое использование, нарушающее нормальную работу сервиса — не разрешены.',
    terms_accept:        'Понятно',
    privacy_title:       'Политика конфиденциальности',
    privacy_collect_label:'Что мы собираем',
    privacy_collect_text: 'При создании аккаунта мы сохраняем ваше <strong>имя пользователя</strong> и <strong>адрес электронной почты</strong>. При создании или прохождении теста мы сохраняем контент и результаты, связанные с вашим аккаунтом. Мы не собираем платёжные данные, геолокацию или что-либо сверх необходимого для работы платформы.',
    privacy_use_label:   'Как мы их используем',
    privacy_use_text:    'Ваши данные используются исключительно для предоставления и улучшения сервиса BlitzIQ — аутентификации аккаунта, отображения ваших тестов и показа результатов сессий. Мы не продаём, не сдаём в аренду и не передаём ваши персональные данные третьим лицам в маркетинговых целях.',
    privacy_cookies_label:'Файлы cookie',
    privacy_cookies_text: 'BlitzIQ использует один файл cookie сессии для поддержания входа в систему. Никаких отслеживающих, аналитических или рекламных сторонних скриптов. Cookie сессии удаляется при выходе из системы или закрытии браузера.',
    privacy_rights_label: 'Ваши права',
    privacy_rights_text:  'Вы можете запросить удаление своего аккаунта и всех связанных данных в любое время, связавшись с нами напрямую. Мы обработаем запрос в разумные сроки и подтвердим выполнение.',
    privacy_accept:      'Понятно',
    toast_not_logged:    'Вы не авторизованы',
    toast_already_logged:'Вы уже авторизованы.',
    error_network:       'Ошибка сети, попробуйте ещё раз.',
    error_generic:       'Что-то пошло не так.',
    nav_theme: 'Тема',
  }
};

function tl(key) {
  const lang = localStorage.getItem('blitziq-lang') || 'en';
  return (TRANSLATIONS_L[lang] && TRANSLATIONS_L[lang][key]) || TRANSLATIONS_L.en[key] || key;
}

function applyLandingTranslations() {
  document.querySelectorAll('[data-il18n]').forEach(el => {
    const key = el.dataset.il18n;
    const val = tl(key);
    if (val) el.innerHTML = val;
  });

  document.querySelectorAll('[data-il18n-text]').forEach(el => {
    const key = el.dataset.il18nText;
    const val = tl(key);
    if (val) el.textContent = val;
  });

  document.querySelectorAll('[data-il18n-placeholder]').forEach(el => {
    const key = el.dataset.il18nPlaceholder;
    const val = tl(key);
    if (val) el.placeholder = val;
  });
}

document.addEventListener('DOMContentLoaded', applyLandingTranslations);
window.applyLandingTranslations = applyLandingTranslations;
window.tl = tl;